#!/bin/bash
# COMMANDES POUR DÉPLOYER SUR RENDER.COM
# Copie-colle ces commandes exactement comme écrites

echo "=== ÉTAPE 1: Générer JWT Secrets ==="
echo ""
echo "Exécutez cette commande 2 FOIS et sauvegardez les résultats:"
echo ""
node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
echo ""
echo "↑ Copiez ce résultat (première clé)"
echo ""
echo "---"
echo ""
node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
echo ""
echo "↑ Copiez ce résultat (deuxième clé)"
echo ""

echo "=== ÉTAPE 2: Configuration Render ==="
echo ""
echo "1. Allez à: https://dashboard.render.com"
echo "2. Cliquez 'New +' → 'Web Service'"
echo "3. Connectez GitHub: millermwr/backend-ista-goma"
echo ""

echo "=== ÉTAPE 3: Paramètres du Service ==="
echo ""
echo "Utilisez EXACTEMENT ces valeurs:"
echo ""
echo "Name:                istag-oma-backend"
echo "Environment:         Node"
echo "Region:              Oregon (US West)"
echo "Branch:              master"
echo "Build Command:       npm install && npm run build"
echo "Start Command:       npm run start:prod"
echo "Plan:                Free (ou Starter)"
echo ""

echo "=== ÉTAPE 4: Variables d'Environnement ==="
echo ""
echo "Ajoutez ces variables dans Render (Add Environment Variable):"
echo ""
echo "NODE_ENV=production"
echo "PORT=3000"
echo "API_PREFIX=api"
echo "API_VERSION=v1"
echo ""
echo "DATABASE_URL_UNPOOLED=postgresql://neondb_owner:npg_SlPUM8c7CbOD@ep-falling-frog-ap9vb20i.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo "DATABASE_URL=postgresql://neondb_owner:npg_SlPUM8c7CbOD@ep-falling-frog-ap9vb20i.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require"
echo ""
echo "JWT_SECRET=<PASTE_YOUR_FIRST_KEY_HERE>"
echo "JWT_EXPIRATION=24h"
echo "JWT_REFRESH_SECRET=<PASTE_YOUR_SECOND_KEY_HERE>"
echo "JWT_REFRESH_EXPIRATION=7d"
echo ""
echo "CORS_ORIGIN=*"
echo "CORS_CREDENTIALS=true"
echo "LOG_LEVEL=info"
echo ""

echo "=== ÉTAPE 5: Tester le Déploiement ==="
echo ""
echo "Après que le statut passe à 'Live', testez:"
echo ""
echo "1. Health Check:"
curl https://istag-oma-backend.onrender.com/api/health
echo ""
echo ""
echo "2. Swagger Docs:"
echo "   https://istag-oma-backend.onrender.com/api/docs"
echo ""
echo "3. Login Test:"
curl -X POST https://istag-oma-backend.onrender.com/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@istagoma.ac.cd","password":"Admin@2024"}'
echo ""
echo ""

echo "=== ÉTAPE 6: Configurer Apps (Mobile + Desktop) ==="
echo ""
echo "Mobile (Gluon) - Éditer ce fichier:"
echo "app-mobile-gluon/src/main/java/com/istagoma/config/ApiConfig.java"
echo ""
echo "Remplacer:"
echo "  API_BASE_URL = \"http://localhost:3000/api/v1\""
echo "Par:"
echo "  API_BASE_URL = \"https://istag-oma-backend.onrender.com/api/v1\""
echo ""
echo "---"
echo ""
echo "Desktop (JavaFX) - Éditer ce fichier:"
echo "app-desktop-javafx/src/main/resources/config.properties"
echo ""
echo "Remplacer:"
echo "  api.url=http://localhost:3000/api/v1"
echo "Par:"
echo "  api.url=https://istag-oma-backend.onrender.com/api/v1"
echo ""

echo "=== ÉTAPE 7: Redéploiement Automatique ==="
echo ""
echo "Maintenant, chaque push redéploie automatiquement:"
echo ""
echo "git add ."
echo "git commit -m \"Feature: Add new endpoint\""
echo "git push origin master"
echo ""
echo "→ Render redéploie automatiquement (5-10 min)"
echo ""

echo "=== LIENS IMPORTANTS ==="
echo ""
echo "Render Dashboard:    https://dashboard.render.com"
echo "Votre API:           https://istag-oma-backend.onrender.com"
echo "API Docs:            https://istag-oma-backend.onrender.com/api/docs"
echo "GitHub Repo:         https://github.com/millermwr/backend-ista-goma"
echo "Render Documentation: https://render.com/docs"
echo ""

echo "✅ DÉPLOIEMENT TERMINÉ!"
